/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d597ff4296275829da6cffcaa5b923a9)
interface __BaseEnv_Env {
	SCREENSHOTS_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	HN42_SCREENSHOT_AGENT_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.output/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "HN42_SCREENSHOT_AGENT_TOKEN">> {}
}
