/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4299ee81d4c453172fae783296c88b32)
interface __BaseEnv_Env {
	SCREENSHOTS_BUCKET: R2Bucket;
	BROWSER: BrowserRun;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.output/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
