/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0a99ceb31acad2d3ef16194fc855a432)
interface __BaseEnv_Env {
	SCREENSHOTS_BUCKET: R2Bucket;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.output/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
