#:schema node_modules/wrangler/config-schema.json
name = "hn42"
account_id = "b704c2550c9082fb06e9796e7c042412"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat"]
main = "./.output/server/index.mjs"
assets = { directory = "./.output/public", binding = "ASSETS" }

[[r2_buckets]]
binding = "SCREENSHOTS_BUCKET"
bucket_name = "hn42-screenshots"
preview_bucket_name = "hn42-screenshots-dev"

[images]
binding = "IMAGES"

[observability]
enabled = true

[placement]
mode = "smart"
