#:schema node_modules/wrangler/config-schema.json
name = "hn-glance"
account_id = "b704c2550c9082fb06e9796e7c042412"
compatibility_date = "2026-07-11"
compatibility_flags = ["nodejs_compat"]
main = "./.output/server/index.mjs"
assets = { directory = "./.output/public", binding = "ASSETS" }

[[r2_buckets]]
binding = "SCREENSHOTS_BUCKET"
bucket_name = "hn-glance-screenshots"
remote = true

[cache]
enabled = true
cross_version_cache = true

[secrets]
required = ["HN_GLANCE_SCREENSHOT_AGENT_TOKEN"]

[observability]
enabled = true

[placement]
mode = "smart"
