/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/screenshot-scheduler/wrangler.jsonc --include-runtime=false --env-interface=SchedulerEnv workers/screenshot-scheduler/worker-configuration.d.ts` (hash: 5e7f542ff43bdb05a2fefbe88339e12e)
interface __BaseEnv_SchedulerEnv {
	SCREENSHOTS_BUCKET: R2Bucket;
	SCREENSHOT_JOBS: Queue;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_SchedulerEnv {}
}
interface SchedulerEnv extends __BaseEnv_SchedulerEnv {}
